
export const AnketaActions = {
  ACTIVATE_SERVICE: 'ACTIVATE_SERVICE',
  ACTIVATE_SIZE: 'ACTIVATE_SIZE',
  ACTIVATE_TIME: 'ACTIVATE_TIME',
  ACTIVATE_BUDGET: 'ACTIVATE_BUDGET',
  ACTIVATE_FORM_DETAILS: 'ACTIVATE_FORM_DETAILS',
  FORM_FINISH: 'FORM_FINISH'
}
